apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: minitube-app
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: minitube
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
