apiVersion: v1
kind: ServiceAccount
metadata:
  name: transcoder
  namespace: minitube-app
  labels:
    app.kubernetes.io/name: transcoder
    app.kubernetes.io/part-of: minitube
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::479213212405:role/minitube-app-irsa-role
